-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, (SUM(os.SALES_AMOUNT) * p.PRICE) as SALES
FROM PRODUCT p JOIN OFFLINE_SALE os ON (p.PRODUCT_ID = os.PRODUCT_ID)
GROUP BY os.PRODUCT_ID
ORDER BY (SUM(os.SALES_AMOUNT) * p.PRICE) DESC, p.PRODUCT_CODE ASC
