-- 코드를 입력하세요
WITH USER_INFO_PART as (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
), PURCHASE_INFO as (
    SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, USER_ID
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT * FROM USER_INFO_PART)
)

SELECT YEAR, MONTH, COUNT(DISTINCT(USER_ID)) as PURCHASED_USERS, ROUND(COUNT(DISTINCT(USER_ID)) / (SELECT COUNT(*) FROM USER_INFO_PART), 1) as PURCHASED_RATIO
FROM PURCHASE_INFO
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC